### ISSUE TITLE
stilleshan/goproxy arm64 does not support --auth-file

### ISSUE THREAD

**Issue by juvechina** [stilleshan/dockerfiles#1]
stilleshan/goproxy arm64 does not support the option of --auth-file,which is used to set up authenticated users

**Comment by stilleshan** [comment]
Please give more description.

**Comment by juvechina** [comment]
> Please give more description.

I run the following command on my ARM box:
docker run -d --name=goproxy --restart=always --network=host stilleshan/goproxy /proxy http --auth-file user:password:0:0: -p :1083 
But running error: unknown long flag '--auth-file'，
the official documents show that it supports user authentication[https://snail007.github.io/goproxy/manual/zh/#/?id=_10%e6%9c%ac%e5%9c%b0%e8%ae%a4%e8%af%81%ef%bc%8c%e9%99%90%e9%80%9f%ef%bc%8c%e6%8e%a7%e5%88%b6%e8%bf%9e%e6%8e%a5%e6%95%b0](url)

**Comment by stilleshan** [comment]
Same problem without docker version . I just tested  official install shell script on centos 7.
Your should submit a issue in official project

**Comment by juvechina** [comment]
> Same problem without docker version . I just tested official install shell script on centos 7.
> Your should submit a issue in official project

yes,the official version does not support ARM, unfortunately

**Comment by stilleshan** [comment]
It is support ARM

https://github.com/snail007/goproxy/releases

**Comment by juvechina** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stilleshan/dockerfiles] stilleshan/goproxy arm64 does not support --auth-file (#1)





 
It is support ARM
 
https://github.com/snail007/goproxy/releases
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
