### ISSUE TITLE
x-ui-ssl镜像可以更新了，xray现在增加了xtls vision流控版本

### ISSUE THREAD

**Issue by jiaoting** [stilleshan/dockerfiles#12]
x-ui-ssl镜像可以更新了，xray现在增加了xtls vision流控版本

**Comment by jiaoting** [comment]
ok，如果有消息了，拜托说下，我也更新下发自我的 iPhone在 2022年11月15日，22:34，Stille ***@***.***> 写道：﻿
x-ui 当初就说不支持 docker, 这个docker不算完美,所以很久也没更新.起码目前能用.
现在新版本我还没测试研究,过几天不忙了试一试,如果可以就更新.

**Comment by stilleshan** [comment]
已更新

**Comment by jiaoting** [comment]
![image](https://user-images.githubusercontent.com/12553424/202074759-9eac49f0-20ac-499b-8431-9e35834668ba.png)
我在原版本上更新了，发现还是没有选项

**Comment by jiaoting** [comment]
我把docker重新删除安装了，发现还是木有
![image](https://user-images.githubusercontent.com/12553424/202075576-a8a8cf28-7053-46dc-a6f0-2954966545c8.png)

**Comment by stilleshan** [comment]
我是拉官方最新代码构建的,我不确定这个功能是否有.

你执行 docker images 查看下镜像的时间

**Comment by jiaoting** [comment]
![image](https://user-images.githubusercontent.com/12553424/202076525-51e5871e-8c31-4edd-ab40-830b9c9f48d2.png)
应该是没有问题呀，你那边能看到是否有新加的协议吗

**Comment by stilleshan** [comment]
我这也没有.你是在哪里看到有新协议加了啊?

**Comment by jiaoting** [comment]
你拉的是FranzKafkaYu的吗？还是[Chasing66](https://github.com/Chasing66)？
https://github.com/FranzKafkaYu/x-ui/releases

https://github.com/vaxilu/x-ui/pull/182

**Comment by stilleshan** [comment]
原版的

难道原版的不维护了?

**Comment by jiaoting** [comment]
原版的一直没见着更新，不过原版里面ssl版本用的是FranzKafkaYu的（他这次倒是更新了），docker化用的[Chasing66](https://github.com/Chasing66)的版本（他也更新了）

**Comment by jiaoting** [comment]
我在这里留了言，两位大神都一并更新了，你可以看看咋弄，你这个docker合并版很好用
https://github.com/vaxilu/x-ui/pull/182

**Comment by jiaoting** [comment]
是不是拉取源改成[Chasing66](https://github.com/Chasing66)？

**Comment by stilleshan** [comment]
https://github.com/Chasing66 用的就是原版的库啊

我尝试换到 FranzKafkaYu 试试

**Comment by stilleshan** [comment]
更新了,依旧没有

**Comment by jiaoting** [comment]
好吧，那就再等等
