### ISSUE TITLE
stilleshan/java_oci_manage:latest 镜像跑不起来 

### ISSUE THREAD

**Issue by eatumom** [stilleshan/dockerfiles#14]
按照docker-compose.yml配置文件配置的
![1](https://user-images.githubusercontent.com/80268544/211139190-7b924702-e90b-4e46-9ddc-f82ce3a8c2be.png)
![2](https://user-images.githubusercontent.com/80268544/211139193-9be87b42-f14b-41a1-8502-005ebcda6d1a.png)

**Comment by stilleshan** [comment]
需要 tty: true 你看下你这个更多设置里有没有

**Comment by eatumom** [comment]
谢谢 在unraid的更多设置额外参数内填入-it就可以了
