### ISSUE TITLE
独角数卡 docker安装提示无法连接数据库

### ISSUE THREAD

**Issue by zhucaidan** [stilleshan/dockerfiles#15]
机器是甲骨文ARM，系统Debian 11，宝塔面板

独角数卡 docker-compose安装提示无法连接数据库

数据库配置错误 :SQLSTATE[HY000] [2002] Connection refused (SQL: select 1 limit 1)

![image](https://user-images.githubusercontent.com/47970938/216871819-a0eb3d83-316a-4def-908b-ef0d56748eee.png)

![image](https://user-images.githubusercontent.com/47970938/216871867-373b967a-96be-491d-a4f1-68babf756724.png)

![image](https://user-images.githubusercontent.com/47970938/216871916-2d745918-a183-4c16-91e8-5b6f1820d2ee.png)

**Comment by stilleshan** [comment]
仔细看教程图
地址是 db 不是 127
