### ISSUE TITLE
stilleshan/vnstat-dashboard 报错

### ISSUE THREAD

**Issue by ghost** [stilleshan/dockerfiles#16]
服务器系统:Debian 11

安装方式:Docker

系统架构:x86_64

Docker参数:`docker run -d \
    --name=vnstat-dashboard \
    --restart=always \
    -p 12345:80 \
    -v /usr/bin/vnstat:/usr/bin/vnstat \
    -v /var/lib/vnstat:/var/lib/vnstat \
    -e TZ=Asia/Shanghai \
    stilleshan/vnstat-dashboard`

报错内容:Fatal error: Uncaught Exception: JSON is invalid in /var/www/html/includes/vnstat.php:60 Stack trace: #0 /var/www/html/includes/vnstat.php(44): vnStat->processVnstatData('') #1 /var/www/html/index.php(37): vnStat->__construct('/usr/bin/vnstat') #2 {main} thrown in /var/www/html/includes/vnstat.php on line 60

![image](https://user-images.githubusercontent.com/96988242/217752893-7b0f63cd-5b75-4354-8366-b67c3ad213c1.png)

**Comment by stilleshan** [comment]
官方项目在 debian 和 ubuntu 下都有问题.没办法.目前只能用在 centos上.

大概率是这两个系统的 vnstat 的安装方式不同,你可以尝试用 https://github.com/vergoh/vnstat/wiki/Install-in-Debian 官方的编译方式安装在使用这个面板试试看.
