### ISSUE TITLE
dockerfiles/sub/start.sh | config.js file path misconfiguration  at line:3

### ISSUE THREAD

**Issue by fengted** [stilleshan/dockerfiles#18]
Configuration file path misconfiguration,  the full path of config.js should be /app/conf/config.js.

**Comment by stilleshan** [comment]
Thanks for your reminder

https://github.com/stilleshan/dockerfiles/commit/f2a3219d0ca1aaab3792106c2626ca1e5ab943c8

https://github.com/stilleshan/dockerfiles/actions/runs/4171631347
