### ISSUE TITLE
dockerproxy.com无法使用

### ISSUE THREAD

**Issue by aogg** [stilleshan/dockerfiles#19]
alpine:~# docker pull dockerproxy.com/a76yyyy/qiandao
Using default tag: latest
Error response from daemon: Get "https://dockerproxy.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
alpine:~# docker pull dockerproxy.com/a76yyyy/qiandao
Using default tag: latest
Error response from daemon: Head "https://dockerproxy.com/v2/a76yyyy/qiandao/manifests/latest": dial tcp 144.24.81.189:443: i/o timeout
alpine:~# docker pull dockerproxy.com/a76yyyy/qiandao
Using default tag: latest
Error response from daemon: Get "https://dockerproxy.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by stilleshan** [comment]
网络问题,稍后在试试吧.

<img width="537" alt="截屏2023-02-19 21 06 21" src="https://user-images.githubusercontent.com/22582966/219949953-01e2e4c0-95a4-46c4-bc5a-ded81ed7d4bc.png">

**Comment by aogg** [comment]
确实，你们这出现偶尔无法使用的情况比较多，要尝试好多好多次后才成功了
