### ISSUE TITLE
你好大神，使用vnstat-dashboard在群晖docker部署时发生错误

### ISSUE THREAD

**Issue by zkhzkhzkh123** [stilleshan/dockerfiles#2]
感谢分享！如题，根据步骤将vnstat-dashboard和vergoh/vnstat安装完毕，vergoh/vnstat运行正常。但是在部署vnstat-dashboard的以后，群晖部署容器成功，但是在群晖容器日志里提示错误，错误是AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message。浏览器开页面也显示
Fatal error: Uncaught Exception: JSON is invalid in /var/www/html/includes/vnstat.php:60 Stack trace: #0 /var/www/html/includes/vnstat.php(44): vnStat->processVnstatData('') #1 /var/www/html/index.php(37): vnStat->__construct('/usr/bin/vnstat') #2 {main} thrown in /var/www/html/includes/vnstat.php on line 60

以下是我执行的yml文件内容
version: '3.2'
services:
  vnstat-dashboard:
    image: stilleshan/vnstat-dashboard
    container_name: vnstat-dashboard
    volumes:
      - /volume1/docker/VnstatDashboard/usr/bin/vnstat:/usr/bin/vnstat
      - /volume1/docker/VnstatDashboard/var/lib/vnstat:/var/lib/vnstat
      - /volume1/docker/VnstatDashboard/var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9991:80
    environment:
      TZ: Asia/Shanghai
    restart: always
根据内容在volume1/docker文件夹中都建好了相应的文件夹。端口有修改。不知其中出了什么问题无法使用。群晖文件夹权限应该全开了。非常感谢！

**Comment by stilleshan** [comment]
看你的 yml 的挂载配置,这几个路径貌似不对吧.
你要挂载 vnstat 的安装路径.我没在群晖上安装过vnstat,所以不太清楚你这个路径是否正确

**Comment by zkhzkhzkh123** [comment]
感谢回复！我是初用群晖docker的小白，群晖的这个路径我也摸不着头脑。在安装vnstat容器的时候，我是新建了文件夹映射了配置路径（不知道这样表达对不），以下是我用的vnstat的配置
docker run -d \
    --restart=unless-stopped \
    --network=host \
    -e HTTP_PORT=8685 \
    -v /volume1/docker/vnstat/etc/TZ:/etc/localtime:ro \
    -v /volume1/docker/vnstat/etc/timezone:/etc/timezone:ro \
    --name vnstat \
    vergoh/vnstat
这样vnstat的运行是可以的
不知道这样我怎么才能挂载dashboard配置文件到安装路径呢？我搜了一下但是没有找到办法能看群晖里面docker container的路径，，，，是不是结构和普通docker不太一样呢

**Comment by stilleshan** [comment]
这是要挂载现有存在的vnstat路径到容器内，并不是创建个挂在目录。

**Comment by zkhzkhzkh123** [comment]
请问我怎么样可以查询到现有的vnstat的路径呢，因为也是通过docker安装的容器，配置文件好像路径也不对。。
