### ISSUE TITLE
请问有计划支持 registry.k8s.io 的代理加速吗

### ISSUE THREAD

**Issue by Huweicai** [stilleshan/dockerfiles#23]
K8S 正在将镜像仓库从 k8s.gcr.io 迁移到 registry.k8s.io，请问站长有计划支持新的仓库地址么？

https://github.com/kubernetes/k8s.io/issues/4780

**Comment by stilleshan** [comment]
过些天有空试试看

**Comment by stilleshan** [comment]
已经更新，请测试下，如有问题请回复。

**Comment by Huweicai** [comment]
很棒，Thanks
