### ISSUE TITLE
subweb 自定义短链接提示 短链接生成失败 请检查短链接服务是否可用

### ISSUE THREAD

**Issue by MurasameCyan** [stilleshan/dockerfiles#25]
没有使用一体化版本 而是分别搭建了subweb  subconverter和MyUrls
单独功能都正常  但是对接subweb和myurls的时候出现问题
subweb搭建时已使用            - 'SHORT_URL=https://s.s.s'  指向了搭建好的myurl 但依然提示生成短链接失败
请问该如何解决?

![image](https://user-images.githubusercontent.com/50967145/230754245-fe35e21f-cefc-4b43-8cae-5158366ae1cf.png)

**Comment by litemini** [comment]
Myurls的反带用了nginx proxy manager 来实现，短链无常正常使用，出现提示“ 短链接生成失败 请检查短链接服务是否可用”；另外长链超过18个vmess节点，clash下载订阅时出现错误。

**Comment by figo2002** [comment]
我用caddy反向代理myurls服务刚开始也是错误，看了log是跨域CORS的header的问题，改了caddyfile解决了, 即加了一行header_down Access-Control-Allow-Origin *
