### ISSUE TITLE
有个地方不是很懂，为什么初始化数据后还要exec进docker容器改密码

### ISSUE THREAD

**Issue by googidaddy** [stilleshan/dockerfiles#26]
exec mysql -uepusdt -pCHANGE_YOUR_PASSWORD epusdt

**Comment by stilleshan** [comment]
按照步骤来
先 docker-compose up -d 启动服务
在
docker exec -i epusdt-db-1 sh -c 'exec mysql -uepusdt -pCHANGE_YOUR_PASSWORD epusdt' < epusdt.sql
这不是改密码，这是因为服务启动了，需要改为你设置的密码进入容器执行后面的 < epusdt.sql 初始化服务

**Comment by googidaddy** [comment]
- ./epusdt:/docker-entrypoint-initdb.d/
将sql文件放到容器中的 /docker-entrypoint-initdb.d/ 目录，就会在mysql第一次启动时执行。之后重启容器不会重复执行
这样子是不是能避免这个操作，能的话我提个pr

**Comment by stilleshan** [comment]
但是 docker-compose down 了之后在 up -d 启动就会又执行了。

**Comment by googidaddy** [comment]
搜了下，好像只有在`docker-compose down -v`这个命令下才会re-active，我先试试，成功了就提pr
