### ISSUE TITLE
sub转换目标为quanx时，[filter_remote]中的地址仍为http://127.0.0.1:25500/

### ISSUE THREAD

**Issue by figo2002** [stilleshan/dockerfiles#29]
sub转换目标为quanx时，[filter_remote]中的地址仍为http://127.0.0.1:25500/，而不是config.js里面设置的api_url地址

**Comment by stilleshan** [comment]
这个只能自行挂载 subconverter 里的 pref.yml 文件，修改 managed_config_prefix 为你的域名。

**Comment by figo2002** [comment]
多谢，解决了，dockerhub里配置文件默认是pref.toml
