### ISSUE TITLE
vnstat-dashboard 已无法兼容新版 vnstat，请大佬更新

### ISSUE THREAD

**Issue by tonyzhou777** [stilleshan/dockerfiles#31]
https://github.com/edirpedro/vnstat-dashboard

找到个新版的 vnstat-dashboard，支持 vnStat 2.10+。

求更新 Docker，谢谢。

**Comment by tonyzhou777** [comment]
大佬还在吗

**Comment by stilleshan** [comment]
完全不同的产品，无法替换。
