### ISSUE TITLE
大佬 怎么没有Snapdrop docker 求上

### ISSUE THREAD

**Issue by lalasou** [stilleshan/dockerfiles#32]
因为 网络环境没联外网，希望能在内网自己部署
谢谢大佬

**Comment by stilleshan** [comment]
https://github.com/RobinLinus/snapdrop

里面有 [docker-compose.yml](https://github.com/RobinLinus/snapdrop/blob/master/docker-compose.yml) 可以用

**Comment by lalasou** [comment]
想要大佬弄好的中文的😂
> https://github.com/RobinLinus/snapdrop
> 
> 
> 
> 里面有 [docker-compose.yml](https://github.com/RobinLinus/snapdrop/blob/master/docker-compose.yml) 可以用
