### ISSUE TITLE
购买商品不会发送邮件

### ISSUE THREAD

**Issue by zswll2** [stilleshan/dockerfiles#34]
您好作者，我按您的方法安装完成后可能正常使用，唯一的问题就是购买商品不会自动发送邮件，请问这个问题如何解决？

**Comment by stilleshan** [comment]
正确配置smtp就可以了，我用的 smtp 是阿里云的邮件ssl 465端口

**Comment by stilleshan** [comment]
还有，只有支付了才会通知，只下单没支付是不会通知的。

**Comment by zswll2** [comment]
我配置没问题，测试是可用发送邮件的， 但是购买后成功支付，是没有邮件提示的。 
网上说可能是进程守护的问题， 请问容器内是否有配置这个？

**Comment by stilleshan** [comment]
docker 已经包含进程守护的。你尝试添加下其他通知服务，如果其他服务能正常通知，说明就是smtp问题

**Comment by zswll2** [comment]
进程守护配置文件和代码在哪里？ 我可能需要修改一下

**Comment by stilleshan** [comment]
https://github.com/stilleshan/dockerfiles/blob/main/dujiaoka/conf/dujiao.conf

**Comment by zswll2** [comment]
https://www.jungley.net/solving-duojiaoshuka-docker-email-issue/
请问如何根据这篇文章修改配置？
