### ISSUE TITLE
sub整合远程配置

### ISSUE THREAD

**Issue by sun-cut** [stilleshan/dockerfiles#35]
你好  我自建的远程配置没有演示站预设那两个配置![image](https://github.com/stilleshan/dockerfiles/assets/84436493/33e79495-08f5-418a-a360-32a5943f4cb3)
![image](https://github.com/stilleshan/dockerfiles/assets/84436493/80c423e2-4b55-46ad-ae52-e9227736a902)
另外能不能自己添加配置在这里显示呢

**Comment by stilleshan** [comment]
fixed https://github.com/stilleshan/dockerfiles/commit/a159a44ea9d28013e400f2121cc2afa248c9ade7

docker 镜像已更新，删除老镜像重新部署。
