### ISSUE TITLE
能否增加一个meta内核的订阅转换后端

### ISSUE THREAD

**Issue by 2275273** [stilleshan/dockerfiles#37]
可否增加一个meta内核的订阅转换后端....原版的不支持vless节点。。https://github.com/MetaCubeX/subconverter   这个是meta内核的作者

**Comment by stilleshan** [comment]
这个我没能力修改开发。只能给原项目提需求了。

**Comment by 2275273** [comment]
这个和原版一样的..只是配置内容不同...你按照你弄原版的方法.把这个meta内核的后端一样弄到docker上就可以了...目前docker上面的项目支持meta内核的都不支持自定义配置...都是写死了规则地址和后端地址....

**Comment by musk1024** [comment]
> 这个和原版一样的..只是配置内容不同...你按照你弄原版的方法.把这个meta内核的后端一样弄到docker上就可以了...目前docker上面的项目支持meta内核的都不支持自定义配置...都是写死了规则地址和后端地址....

[musk1024/sub](https://github.com/musk1024/sub)

Fork from stilleshan/sub, Add support for clash meta & singbox

**Comment by stilleshan** [comment]
近期没时间更新这个了，方便可以提交pr，谢谢。
