### ISSUE TITLE
sub后端不起作用？

### ISSUE THREAD

**Issue by falltree** [stilleshan/dockerfiles#43]
在局域网一台debian部署了sub，描述是包含前端和后端和短链接，debian ip为192.168.1.10
但本机电脑访问web界面显示的后端是127.0.0.1:25500，这个是本机电脑的后端，如果运行本机win版subconverter，是可以运行的。
但如果后端改成192.168.1.10:25500，就无法运行，理论上debian里面的sub 不是应该已经包含了后端吗？

另外如果docker部署 subweb+subconverter，把subconverter的后端地址输入subweb，是可以运行的，但是又不支持vless，还是只能用本机的win版支持vless的subconverter来作为后端。

希望能实现在docker同时包含前端和后端，并且支持vless的subconverter

**Comment by stilleshan** [comment]
修改 conf/config.js 文件， apiUrl: 'http://127.0.0.1:25500', 改为你的内网IP apiUrl: 'http://192.168.1.10:25500',

**Comment by falltree** [comment]
无论是修改config.js，还是在web页面直接手动设置后端地址，打开转换链接都报错。
几个月前部署过一次，也是这样。似乎sub里面自带的后端根本没起作用，但是docker部署和运行又很正常。

只有分别部署subweb和subconverter时，才可以正常转换。或者subweb+本地subconverter或其他人的docker版sunbconverter也可以正常转换。

> 修改 conf/config.js 文件， apiUrl: 'http://127.0.0.1:25500', 改为你的内网IP apiUrl: 'http://192.168.1.10:25500',

**Comment by stilleshan** [comment]
你问的是 sub 整合项目的话，不适合你这个需求，你还是单独部署。这个整合的是需要用域名反向代理的。

![截屏2024-10-05 10 20 23](https://github.com/user-attachments/assets/7af6499d-0a2e-438b-b4b5-6702059f1e71)

**Comment by falltree** [comment]
可能是我对sub项目理解不对？我理解是只需要docker部署一个项目sub，既包含了前端也包含了后端，短链接属于可选。 打开sub项目的前端，输入订阅或节点信息，然后由同一个项目进行后端转换。现在实际结果是无法成功，打开转换后的链接ip:25500/xxxxxxxxxxxxxxxxxxx，显示拒绝访问。
这不是域名反代的问题，我只是本地局域网部署，直接ip就够用了。还是说sub项目的后端转换，必须要域名反代才能工作？不能直接ip访问？

我是用很老的机器i3-4030u 安装的PVE，再运行debian虚拟机，分开部署的确是可以，但需要部署两个docker容易，一个前端一个后端，对于虚拟机的负担可能会更大，所以希望能只部署一个docker容器，同时实现前端和后端的功能。

> 你问的是 sub 整合项目的话，不适合你这个需求，你还是单独部署。这个整合的是需要用域名反向代理的。
> 
> ![截屏2024-10-05 10 20 23](https://private-user-images.githubusercontent.com/22582966/373837252-7af6499d-0a2e-438b-b4b5-6702059f1e71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDUyNzgsIm5iZiI6MTcyODIwNDk3OCwicGF0aCI6Ii8yMjU4Mjk2Ni8zNzM4MzcyNTItN2FmNjQ5OWQtMGEyZS00MzhiLWI0YjUtNjcwMjA1OWYxZTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA4NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZGI1ZDg4MzlhNDA3MmJlNzhkMjg2MWMwMTVhMjZlM2Q4NzM4NThhODVlMTE1NzA5MjZmNmUwOTIyZTAyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Aitjb2-f-k6NsgcDip0tcLXhHv3jQKfB0EEGDwb4ZS0)

**Comment by stilleshan** [comment]
这个项目并不是你的这个需求，你的需求其实很简单，只需要一个 docker-compose 把前段和后端2个容器一起启动，改下js里的IP地址就可以了。

而这个项目里的sub整合，主要是为了加入域名的需求。所以请求127.0.0.1:25500，是这个容器内的nginx请求自身容器里的25500后端服务，

就你说的i3的pve部署2个容器，可以说完全没任何压力的。

**Comment by falltree** [comment]
行吧，不折腾那么多了，需要用时就部署前端+后端
