### ISSUE TITLE
大佬，能否帮个忙将思源笔记的docker修改为支持arm64呢？

### ISSUE THREAD

**Issue by chenryace** [stilleshan/dockerfiles#5]
是这样的，我的服务器是ARM64架构的armbian(无图形)，然后在网上也查到了很多攻略，像ARM64架构的M1要用到amd64的docker，可以通过buildx 实现，我基本都明白了个也了解了个大概。因为要运行-- boostrap这一步，就是docker login这一步被卡得死死的，error storing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`.查了这个bug是linux的硬伤，要装PASS和gnupg2,然后这两个活宝死活装不上。估计跟国内源有关系，修改完还是装不上...实在没办法自己动手丰衣足食。
希望您能帮助一下。谢谢

**Comment by stilleshan** [comment]
看了下他的程序是闭源的,无法构建镜像.

**Comment by chenryace** [comment]
> 看了下他的程序是闭源的,无法构建镜像.

哦，好的，劳您费心了。还以为构建一个新的dockerfiles很简单，是我学习不足了
