### ISSUE TITLE
我是 ZFile 的作者，关于 ZFile Dockerfile 的一点建议

### ISSUE THREAD

**Issue by zhaojun1998** [stilleshan/dockerfiles#6]
我记得您是开始为 `ZFile` 提供 `Docker` 镜像的，还给我提过 `issue`，非常感谢。

经过学习和探索，对 `ZFile` 镜像做了一些优化，可以大幅降低内存占用。
主要是切换了 `base` 镜像为 `ibm-semeru-runtimes:open-8-jre` ，这是 `IBM` 维护的 `OpenJ9 JVM`，相较于传统的 `JVM` 大幅降低了内存占用，并会自动检测 `docker` 环境做一些优化。

您维护的 `Dockerfile` 中如果有其他 `Java` 项目也可以尝试切换此 `Base Image` 来降低资源占用。

相关链接：

- [ibm-semeru-runtimes  docker hub](https://hub.docker.com/_/ibm-semeru-runtimes)
- [博客文档 - 比对传统镜像和 IBM 镜像资源占用](https://zhaojun.vip/archives/42/)

**Comment by stilleshan** [comment]
谢谢,已测试并更新,之前由于你用的 base 镜像不支持 arm, 我还研究了半天 base 镜像哪个更好.

https://github.com/stilleshan/dockerfiles/commit/6154daa982600770a9d1f0cb4367975638ed4aa0

**Comment by zhaojun1998** [comment]
@stilleshan 

我之前也不太懂，而且没有 `arm` 机器，就没注意到，最近有一台 `oracle arm`，正好完善了下，这个 `base` 镜像，支持 `amd`、`arm` 而且各个版本的 `java` 都有
