### ISSUE TITLE
请求更新 speedtest-x 镜像

### ISSUE THREAD

**Issue by BadApple9** [stilleshan/dockerfiles#8]
speedtest-x 目前的镜像使用的代码已不是最新版本，请求更新。（旧版本引入的字节跳动 CDN 出现 bug，会导致一些问题）
仓库地址：https://github.com/BadApple9/speedtest-x

谢谢~

**Comment by BadApple9** [comment]
我直接发 PR 吧

**Comment by stilleshan** [comment]
谢谢大佬的提醒，亲自来催更了。😂

**Comment by stilleshan** [comment]
已经在build了。

**Comment by stilleshan** [comment]
下次可以直接pr....幸苦

**Comment by BadApple9** [comment]
好巧，多谢~
