### ISSUE TITLE
你好！关于stilleshan/webdav的config.yml挂载问题

### ISSUE THREAD

**Issue by leon7786** [stilleshan/dockerfiles#9]
你好~关于此项目，我用docker run -d --name=webdav --restart=always -v /path/config.yml:/config.yml -p 8080:8080 stilleshan/webdav能跑起来，但请求config.yml 范例

config.yml我改来改去都读不到，webdav进不去~

感觉docker化，config.yml要改超多地方，水平不够改不正确~

**Comment by stilleshan** [comment]
/path/config.yml:/config.yml

你挂载路径是不是对的? 这个只是示例,这个默认config.yml肯定是可以跑起来的.

**Comment by leon7786** [comment]
能读到config.yml，只是官方config.yml范例拿来用改很多地方，刚刚找了个群友帮忙改成了~
另外还要补上-v /home/gdrive:/data

docker run -d --name=webdav1 --restart=always -v /home/www/docker/webdav-hacdias/config.yml:/config.yml -v /home/gdrive:/data -p 28080:8080 stilleshan/webdav
